# https://github.com/railwayapp/nixpacks/issues/1340#issuecomment-3084046921
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
  nixpkgsArchive = '11cb3517b3af6af300dd6c055aeda73c9bf52c48'
